# Generated by Django 4.1.6 on 2023-02-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, verbose_name='Backup name')),
                ('location', models.TextField(verbose_name='Backup Location')),
                ('last_backup_start_time', models.TextField(verbose_name='Date last update started')),
                ('last_backup_end_time', models.TextField(verbose_name='Date last update ended')),
                ('config', models.TextField(verbose_name='Backup Config')),
            ],
        ),
    ]
