# Generated by Django 2.2.4 on 2019-09-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidFTPBackup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='DateBackup',
        ),
    ]
