# Generated by Django 2.2.4 on 2019-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidFTPBackup', '0002_auto_20190903_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='Date last updated')),
            ],
        ),
        migrations.DeleteModel(
            name='DateBackup',
        ),
    ]
